motd = """
Welcome to my MUD server
Have a great time here!
"""

[[listener]]
bind = "0.0.0.0:7878"

[limits]
max-in-flight-msgs = 1024

[logging]
filter = "info"

[database]
host = "localhost"
dbname = "tommo"
